# Site settings
title: DARA - Department of Astrofauna and Abilities
description: Information and Database for the War Drums Webcomic Series
baseurl: "/dara-info"
url: "https://edenjtait.github.io"

# Collections
collections:
  species:
    output: true
    permalink: /species/:path/

# Build settings
markdown: kramdown
